server:
  port: 8762

spring:
  application:
    name: zuul-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/


zuul:
  routes:
    auth-service:
      path: /login/**
      url: http://127.0.0.1:9101/
      service-id: auth-service
      sensitive-headers: Cookie,Set-Cookie
      stripPrefix: false

    backend-service:
      path: /backend/**
      url: http://127.0.0.1:9102/

    Library-Api-Service :
      path: /back/**
      url: http://127.0.0.1:8081/
  ignored-services: *

shuaicj.security.jwt.secret: otherpeopledontknowit

ribbon:
  ReadTimeout: 60000
