server:
  port: 9100
spring:
  application:
    name: auth-service

shuaicj.security.jwt.secret: otherpeopledontknowit

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
